
select * 
from customer 
limit 20;

--Q1 What is the total revenue generated by female vs male customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
order by revenue desc;

--Q2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- OR 

WITH avg_spend AS (
    SELECT AVG(purchase_amount) AS avg_purchase
    FROM customer
)
SELECT customer_id, purchase_amount
FROM customer, avg_spend
WHERE discount_applied = 'Yes'
AND purchase_amount >= avg_spend.avg_purchase;


--Q3 Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "avg_product_rating"
from customer
group by item_purchased
order by avg_product_rating desc
limit 5;

--Q4 Compare the average purchase amounts between Standard and Express shipping.
select shipping_type,
round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg_purchase_amount desc;

--Q5 Do subscibed customers spend more? Compare average speed and total revenue between subscribers snf non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6  Which 5 products have a highest percentage of purchase with the discouns applied?
select item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 Segment customers into New, Returning, and Loyal based on their total numbers of previous purchases, and show the count of each segment.
WITH customer_type as(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, COUNT(DISTINCT customer_id) as "Number of Customers"
from customer_type
group by customer_segment;


--Q8 What are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as product_rank
from customer
group by category, item_purchased
)
select product_rank, item_purchased, category, total_orders
from item_counts
where product_rank<= 3;

--Q9 Are customers who are the repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers,
ROUND(100.0* COUNT(customer_id)/SUM(COUNT(customer_id))OVER(),2
) AS repeat_buyer_percentage
from customer
where previous_purchases > 5
group by subscription_status;     -- raw data-> decision metric


--Q10 What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue,
ROUND(SUM(purchase_amount) / COUNT(customer_id),2) AS avg_revenue_per_customer
from customer
group by age_group
order by total_revenue desc;

-- KPIs
--What is the overall health of customer transactions in terms of revenue,
--order value, and customer dissatisfaction

select count(*) as total_transaction,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as avg_order_value,
round(100.0 *sum(case when low_review_flag = 1 then 1 else 0 end)/count(*),
2) as low_review_rate
from customer;